In [6]:
import numpy as np

In [7]:
np1 = np.array([1,2,3])

In [8]:
#build a array

In [9]:
np1

array([1, 2, 3])

In [10]:
np2 = np.array([2,5,6])

In [30]:
np1+np2

array([3, 7, 9])

In [12]:
print(np1.ndim, np1.shape, np1.dtype)

1 (3,) int32


In [31]:
np.dot(np1, np2)

30

In [13]:
#one dimension, three element, datatype of element

In [14]:
np3 = np.zeros([2,3])
np3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
#build a zero array (similar as .ones)

In [16]:
np3=np3.reshape([3,2])

In [17]:
np3

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
np3 = np3.astype('float16')

In [19]:
np3

array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float16)

In [23]:
np4 = np.array([[1, 2, 3], [4, 5, 6]])

In [25]:
print(np4[1][2])

6


In [26]:
print(np4>3)
print(np4[np4>2])

[[False False False]
 [ True  True  True]]
[3 4 5 6]


In [29]:
print(np4.sum(axis=1))
print(np4.sum(axis=0))

[ 6 15]
[5 7 9]


In [ ]:
#橫加 直加